package graph

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.78

import (
	"context"

	"github.com/takanoriyanagitani/go-docker-containers2ql/graph/model"
)

// Health is the resolver for the health field.
func (r *basicInfoOutputResolver) Health(ctx context.Context, obj *model.BasicInfoOutput) (*model.Health, error) {
	return r.Resolver.Health(ctx, obj)
}

// BasicInfo is the resolver for the basicInfo field.
func (r *queryResolver) BasicInfo(ctx context.Context, input *model.BasicInfoInput) ([]*model.BasicInfoOutput, error) {
	return r.Resolver.BasicInfo(ctx, input)
}

// BasicInfoOutput returns BasicInfoOutputResolver implementation.
func (r *Resolver) BasicInfoOutput() BasicInfoOutputResolver { return &basicInfoOutputResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

type basicInfoOutputResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
